from django.db import migrations, models
import django.db.models.deletion
import django.conf


def seed_subscriptions(apps, schema_editor):
    Company = apps.get_model('accounts','Company')
    Subscription = apps.get_model('accounts','Subscription')
    for company in Company.objects.all():
        Subscription.objects.get_or_create(company_id=company.id, defaults={'status':'trial','currency':'USD'})

class Migration(migrations.Migration):
    dependencies=[('accounts', '0002_user_roles_and_department_manager')]
    operations=[
        migrations.CreateModel(name='Subscription',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('trial','Trial'),('active','Active'),('past_due','Past due'),('cancelled','Cancelled')],default='trial',max_length=20)),('billing_cycle',models.CharField(choices=[('monthly','Monthly'),('annual','Annual')],default='monthly',max_length=10)),('monthly_price',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('currency',models.CharField(default='USD',max_length=10)),('started_at',models.DateTimeField(blank=True,null=True)),('renews_at',models.DateTimeField(blank=True,null=True)),('cancelled_at',models.DateTimeField(blank=True,null=True)),('external_customer_id',models.CharField(blank=True,max_length=150)),('external_subscription_id',models.CharField(blank=True,max_length=150)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='subscription',to='accounts.company'))]),
        migrations.CreateModel(name='AuditLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(choices=[('create','Create'),('update','Update'),('activate','Activate'),('suspend','Suspend'),('login','Login'),('invite','Invite'),('system','System')],default='system',max_length=20)),('target_type',models.CharField(blank=True,max_length=80)),('target_id',models.CharField(blank=True,max_length=80)),('message',models.CharField(max_length=500)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='audit_actions',to=django.conf.settings.AUTH_USER_MODEL)),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='audit_logs',to='accounts.company'))]),
        migrations.CreateModel(name='SuspensionEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('reason',models.CharField(max_length=255)),('notes',models.TextField(blank=True)),('started_at',models.DateTimeField(auto_now_add=True)),('ended_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='suspensions',to='accounts.company')),('suspended_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=django.conf.settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='PlatformNotification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('message',models.TextField()),('level',models.CharField(choices=[('info','Info'),('success','Success'),('warning','Warning'),('danger','Urgent')],default='info',max_length=10)),('created_at',models.DateTimeField(auto_now_add=True)),('expires_at',models.DateTimeField(blank=True,null=True)),('is_active',models.BooleanField(default=True)),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='platform_notifications',to='accounts.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=django.conf.settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='SupportTicket',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('subject',models.CharField(max_length=180)),('description',models.TextField()),('status',models.CharField(choices=[('open','Open'),('in_progress','In progress'),('waiting','Waiting'),('resolved','Resolved')],default='open',max_length=20)),('priority',models.CharField(choices=[('low','Low'),('normal','Normal'),('high','High'),('urgent','Urgent')],default='normal',max_length=10)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('resolved_at',models.DateTimeField(blank=True,null=True)),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='support_tickets_assigned',to=django.conf.settings.AUTH_USER_MODEL)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='support_tickets',to='accounts.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='support_tickets_created',to=django.conf.settings.AUTH_USER_MODEL))]),
        migrations.RunPython(seed_subscriptions, migrations.RunPython.noop),
    ]
