# Generated by Django 5.2.17 on 2026-09-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_security_billing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='platformnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='suspensionevent',
            options={'ordering': ['-started_at']},
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_company_54fc08_idx',
            old_name='accounts_audit_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_action_f18cdc_idx',
            old_name='accounts_audit_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_target__0c7dca_idx',
            old_name='accounts_audit_target_idx',
        ),
        migrations.RenameIndex(
            model_name='billinginvoice',
            new_name='accounts_bi_company_02cdab_idx',
            old_name='accounts_bil_company_4a0e2f_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('suspend', 'Suspend'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('invite', 'Invite'), ('permission_change', 'Permission change'), ('salary_change', 'Salary change'), ('termination', 'Termination'), ('contract_change', 'Contract change'), ('payroll_process', 'Payroll process'), ('payroll_approve', 'Payroll approval'), ('payroll_payment', 'Payroll payment'), ('system', 'System'), ('security', 'Security event'), ('integration_import', 'Integration import'), ('integration_rollback', 'Integration rollback'), ('account_status', 'Account status'), ('data_export', 'Data export'), ('disciplinary_action', 'Disciplinary action'), ('leave_approve', 'Leave approval'), ('leave_reject', 'Leave rejection')], default='system', max_length=30),
        ),
    ]
