# Generated by Django 5.2.17 on 2026-09-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='provider',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('stripe', 'Stripe'), ('paddle', 'Paddle')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('stripe', 'Stripe'), ('paddle', 'Paddle')], default='manual', max_length=20),
        ),
    ]
