# Generated by Django 5.2.17 on 2026-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_site_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('professional', 'Professional'), ('scale', 'Scale'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
