# Generated by Django 5.2.17 on 2026-10-04 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('encrypted_password', models.TextField(blank=True)),
                ('use_tls', models.BooleanField(default=True, help_text='STARTTLS on an existing connection. Mutually exclusive with SSL.')),
                ('use_ssl', models.BooleanField(default=False, help_text='Implicit TLS from the first byte, usually port 465. Mutually exclusive with TLS.')),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email configuration',
            },
        ),
    ]
