# Generated by Django 5.2.17 on 2026-10-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_emailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpage',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Overrides the description a crawler sees. Aim for 140-160.', max_length=320),
        ),
        migrations.AddField(
            model_name='marketingpage',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Overrides the title a crawler sees. Aim for 50-60 characters.', max_length=120),
        ),
        migrations.AddField(
            model_name='marketingpage',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Keep out of search engines, and out of sitemap.xml.'),
        ),
        migrations.AddField(
            model_name='marketingpage',
            name='og_image_url',
            field=models.CharField(blank=True, default='', help_text='Absolute URL of the link-preview image. Blank shares without one.', max_length=500),
        ),
    ]
