from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[('accounts','0009_advanced_platform_admin'),('employees','0006_required_document_rule_constraints'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='HRNotification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('notification_type',models.CharField(choices=[('compliance','Compliance'),('contract','Contract'),('onboarding','Onboarding'),('leave','Leave'),('employee','Employee'),('payroll','Payroll'),('system','System')],default='system',max_length=20)),('level',models.CharField(choices=[('info','Info'),('success','Success'),('warning','Warning'),('danger','Urgent')],default='info',max_length=10)),('title',models.CharField(max_length=200)),('message',models.TextField()),('action_url',models.CharField(blank=True,max_length=300)),('due_date',models.DateField(blank=True,null=True)),('dedupe_key',models.CharField(blank=True,max_length=255)),('read_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='hr_notifications',to='accounts.company')),('employee',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='hr_notifications',to='employees.employee')),('recipient',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='hr_notifications',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='WorkflowRule',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('event_type',models.CharField(choices=[('employee_created','Employee created'),('contract_expiring','Contract expiring'),('compliance_alert','Compliance alert'),('leave_submitted','Leave submitted')],max_length=30)),('name',models.CharField(max_length=180)),('enabled',models.BooleanField(default=True)),('create_task',models.BooleanField(default=True)),('send_notification',models.BooleanField(default=True)),('task_type',models.CharField(choices=[('onboarding','Onboarding'),('offboarding','Offboarding'),('compliance','Compliance'),('contract','Contract renewal'),('leave','Leave'),('hr','HR task')],default='hr',max_length=20)),('priority',models.CharField(choices=[('low','Low'),('normal','Normal'),('high','High'),('urgent','Urgent')],default='normal',max_length=10)),('days_before',models.PositiveIntegerField(default=30)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='workflow_rules',to='accounts.company'))]),
        migrations.CreateModel(name='WorkflowTask',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('task_type',models.CharField(choices=[('onboarding','Onboarding'),('offboarding','Offboarding'),('compliance','Compliance'),('contract','Contract renewal'),('leave','Leave'),('hr','HR task')],default='hr',max_length=20)),('title',models.CharField(max_length=200)),('description',models.TextField(blank=True)),('priority',models.CharField(choices=[('low','Low'),('normal','Normal'),('high','High'),('urgent','Urgent')],default='normal',max_length=10)),('status',models.CharField(choices=[('open','Open'),('in_progress','In progress'),('completed','Completed'),('cancelled','Cancelled')],default='open',max_length=20)),('due_date',models.DateField(blank=True,null=True)),('source_type',models.CharField(blank=True,max_length=60)),('source_id',models.CharField(blank=True,max_length=60)),('created_at',models.DateTimeField(auto_now_add=True)),('completed_at',models.DateTimeField(blank=True,null=True)),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assigned_hr_tasks',to=settings.AUTH_USER_MODEL)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='workflow_tasks',to='accounts.company')),('employee',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='workflow_tasks',to='employees.employee'))]),
        migrations.AddConstraint(model_name='hrnotification',constraint=models.UniqueConstraint(condition=~models.Q(dedupe_key=''),fields=('recipient','dedupe_key'),name='unique_notification_dedupe')),
        migrations.AddConstraint(model_name='workflowrule',constraint=models.UniqueConstraint(fields=('company','event_type','name'),name='unique_workflow_rule_name')),
        migrations.AddIndex(model_name='hrnotification',index=models.Index(fields=['recipient','read_at'],name='workflows_hr_recipient_idx')),
        migrations.AddIndex(model_name='hrnotification',index=models.Index(fields=['company','notification_type','due_date'],name='workflows_hr_due_idx')),
        migrations.AddIndex(model_name='workflowtask',index=models.Index(fields=['company','status','due_date'],name='workflows_task_due_idx')),
    ]
