# Generated by Django 5.2.17 on 2026-09-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workflowrule',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workflowtask',
            options={'ordering': ['status', 'due_date', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='hrnotification',
            new_name='workflows_h_recipie_597959_idx',
            old_name='workflows_hr_recipient_idx',
        ),
        migrations.RenameIndex(
            model_name='hrnotification',
            new_name='workflows_h_company_2189c5_idx',
            old_name='workflows_hr_due_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtask',
            new_name='workflows_w_company_e64acd_idx',
            old_name='workflows_task_due_idx',
        ),
    ]
