# Generated by Django 5.2.17 on 2026-09-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_provider_config'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='syncevent',
            name='sync_event_queue_idx',
        ),
        migrations.RenameIndex(
            model_name='externalrecord',
            new_name='integration_connect_2fa844_idx',
            old_name='integrations_connection_idx',
        ),
    ]
