"""PDF generation for leave and break request forms (employee copy)."""
from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _styles():
    base = getSampleStyleSheet()
    return {
        'title': ParagraphStyle('TitleCustom', parent=base['Title'], fontSize=16, spaceAfter=4),
        'heading': ParagraphStyle('HeadingCustom', parent=base['Heading2'], fontSize=12, spaceAfter=6, textColor=colors.HexColor('#0f766e')),
        'normal': base['Normal'],
        'muted': ParagraphStyle('Muted', parent=base['Normal'], textColor=colors.HexColor('#64748b'), fontSize=9),
        'copy': ParagraphStyle('CopyBanner', parent=base['Normal'], fontSize=11, textColor=colors.HexColor('#b45309'), alignment=1, spaceBefore=4, spaceAfter=8),
    }


def build_break_request_pdf(break_request, copy_label='EMPLOYEE COPY'):
    """Generate a printable break request form PDF for the employee."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=16 * mm, leftMargin=16 * mm,
        topMargin=14 * mm, bottomMargin=14 * mm,
    )
    styles = _styles()
    company = break_request.employee.company
    emp = break_request.employee
    duration = break_request.duration_minutes
    duration_str = f'{duration} minutes' if duration is not None else '—'

    story = []
    from accounts.pdf_utils import company_logo_image
    logo = company_logo_image(company)
    if logo is not None:
        story.append(logo)
    story += [
        Paragraph(company.name, styles['title']),
        Paragraph('Break Request Form', styles['heading']),
        Paragraph(copy_label, styles['copy']),
        Spacer(1, 6),
    ]

    details = [
        ['Employee name', emp.full_name],
        ['Employee code', getattr(emp, 'employee_code', '') or '—'],
        ['Department', getattr(emp, 'department', '') or '—'],
        ['Break type', break_request.get_break_type_display()],
        ['Date', str(break_request.date)],
        ['Start time', str(break_request.start_time)[:5]],
        ['End time', str(break_request.end_time)[:5] if break_request.end_time else '—'],
        ['Duration', duration_str],
        ['Status', break_request.get_status_display()],
        ['Reason', break_request.reason or '—'],
        ['Applied at', break_request.applied_at.strftime('%Y-%m-%d %H:%M') if break_request.applied_at else '—'],
        ['Reviewed by', break_request.reviewed_by.username if break_request.reviewed_by else '—'],
    ]
    table = Table(details, colWidths=[45 * mm, 125 * mm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0fdfa')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#cbd5e1')),
        ('PADDING', (0, 0), (-1, -1), 7),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story += [table, Spacer(1, 16)]

    story.append(Paragraph('Signatures', styles['heading']))
    sig = Table([
        ['Employee signature', '________________________', 'Date', '____________'],
        ['Manager / HR signature', '________________________', 'Date', '____________'],
    ], colWidths=[40 * mm, 55 * mm, 20 * mm, 40 * mm])
    sig.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
    ]))
    story += [sig, Spacer(1, 18)]
    story.append(Paragraph(
        f'Generated by HRCloudPay on {datetime.utcnow().strftime("%Y-%m-%d %H:%M")} UTC · {copy_label}',
        styles['muted'],
    ))
    doc.build(story)
    return buffer.getvalue()


def build_leave_request_pdf(leave_request, copy_label='EMPLOYEE COPY'):
    """
    Renders the Employee Leave/Break-Off Request Form in the same shape
    used on paper HR forms across the region: a details grid, a reason
    box, and a four-row approval/signature table - populated from this
    company's own data.
    """
    from datetime import timedelta

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=18 * mm, leftMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
    )
    base = getSampleStyleSheet()
    center_title = ParagraphStyle('CenterTitle', parent=base['Heading2'], alignment=1)
    small = ParagraphStyle('Small', parent=base['Normal'], fontSize=8, leading=11, textColor=colors.HexColor('#475569'))
    copy_style = ParagraphStyle('CopyBanner', parent=base['Normal'], fontSize=10, alignment=1, textColor=colors.HexColor('#b45309'), spaceAfter=6)

    employee = leave_request.employee
    company = employee.company
    contract = employee.current_contract
    employment_status = contract.get_contract_type_display() if contract else employee.get_employment_status_display()
    return_date = leave_request.end_date + timedelta(days=1)
    paid = 'No' if leave_request.leave_type == 'unpaid' else 'Yes'

    story = [
        Paragraph(company.name, base['Title']),
        Paragraph('Department of Human Resources', base['Normal']),
        Spacer(1, 4),
        Paragraph('EMPLOYEE LEAVE / BREAK-OFF REQUEST FORM', center_title),
        Paragraph(copy_label, copy_style),
        Spacer(1, 6),
    ]

    LABEL_BG_LOCAL = colors.HexColor('#eef2ff')
    BORDER_LOCAL = colors.HexColor('#94a3b8')

    details = [
        ['Leave/Break Request Date', str(leave_request.applied_at.date()), 'Type of Leave/Break', leave_request.get_leave_type_display()],
        ["Employee's Name", employee.full_name, 'Date of Contract/Employment', str(employee.hire_date or '-')],
        ['Department', employee.effective_department or '-', 'Job Title', employee.job_title or '-'],
        ['ID/Emp Nos', f"{employee.id_card_no or '-'} / {employee.employee_code}", 'Duty Station', employee.pay_point or '-'],
        ['Employment Status', employment_status, 'Duration', f"{leave_request.days_requested} day(s)"],
        ['Leave/Break Starting Date', str(leave_request.start_date), 'Ending Date', str(leave_request.end_date)],
        ['Date of Return to Duty/Work', str(return_date), 'Paid or Unpaid Leave/Break', paid],
    ]
    details_table = Table(details, colWidths=[42 * mm, 43 * mm, 42 * mm, 43 * mm])
    details_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), LABEL_BG_LOCAL),
        ('BACKGROUND', (2, 0), (2, -1), LABEL_BG_LOCAL),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (2, 0), (2, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER_LOCAL),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('PADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story += [details_table, Spacer(1, 8)]

    reason_table = Table(
        [['Reason(s) for Leave/Break-Off Request'], [leave_request.reason or '-']],
        colWidths=[170 * mm], rowHeights=[8 * mm, 16 * mm],
    )
    reason_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), LABEL_BG_LOCAL),
        ('FONTNAME', (0, 0), (0, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER_LOCAL),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 1), (0, 1), 'TOP'),
    ]))
    story += [reason_table, Spacer(1, 10)]

    reviewer_name = leave_request.reviewed_by.username if leave_request.reviewed_by else ''
    review_status = leave_request.get_status_display()
    review_date = str(leave_request.applied_at.date()) if leave_request.status != 'pending' else ''
    approver_rows = [
        ['Approval', 'Name', 'Signature/Status', 'Date'],
        ['Employee', employee.full_name, 'Submitted', str(leave_request.applied_at.date())],
        ['Supervisor / Department Manager', reviewer_name, review_status, review_date],
        ['HR', '', '', ''],
    ]
    approval_table = Table(approver_rows, colWidths=[52 * mm, 42 * mm, 42 * mm, 34 * mm], rowHeights=[9 * mm, 11 * mm, 11 * mm, 11 * mm])
    approval_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3a8a')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER_LOCAL),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story += [approval_table, Spacer(1, 12)]

    note = (
        "Note: All requests should be submitted with as much advance notice as your leave "
        "type requires, except for urgent compassionate cases. Any time taken beyond an "
        "approved request may be treated as unauthorized absence under your company's "
        "attendance policy."
    )
    story += [Paragraph(note, small), Spacer(1, 8), Paragraph(f'Generated by {company.name} via HRCloudPay · {copy_label}', small)]

    doc.build(story)
    return buffer.getvalue()
