# Generated by Django 5.2.17 on 2026-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='crossed_midnight',
            field=models.BooleanField(default=False),
        ),
    ]
