from django.db import migrations, models
import django.db.models.deletion
import uuid

def fkey(model, related_name, null=False): return models.ForeignKey(model, null=null, blank=null, on_delete=django.db.models.deletion.CASCADE if not null else django.db.models.deletion.SET_NULL, related_name=related_name)
class Migration(migrations.Migration):
    initial=True
    dependencies=[('accounts','0015_merge_security_billing')]
    operations=[
      migrations.CreateModel(name='SecuritySession',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('secret_hash',models.CharField(max_length=64,unique=True)),('ip_address',models.GenericIPAddressField(blank=True,null=True)),('country',models.CharField(blank=True,max_length=100)),('user_agent',models.TextField(blank=True)),('device_label',models.CharField(blank=True,max_length=200)),('created_at',models.DateTimeField(auto_now_add=True)),('last_seen_at',models.DateTimeField(auto_now=True)),('expires_at',models.DateTimeField()),('revoked_at',models.DateTimeField(blank=True,null=True)),('mfa_verified',models.BooleanField(default=False)),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='security_sessions',to='accounts.company')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='security_sessions',to='accounts.user'))]),
      migrations.CreateModel(name='MFADevice',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('secret_encrypted',models.TextField()),('enabled',models.BooleanField(default=False)),('required',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='mfa_device',to='accounts.user'))]),
      migrations.CreateModel(name='RecoveryCode',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code_hash',models.CharField(max_length=64,unique=True)),('used_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='recovery_codes',to='accounts.user'))]),
      migrations.CreateModel(name='SecurityEvent',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('event_type',models.CharField(max_length=120)),('severity',models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High'),('critical','Critical')],default='low',max_length=20)),('message',models.TextField()),('ip_address',models.GenericIPAddressField(blank=True,null=True)),('user_agent',models.TextField(blank=True)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='security_events',to='accounts.user')),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='security_events',to='accounts.company'))]),
      migrations.CreateModel(name='SecurityIncident',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('title',models.CharField(max_length=255)),('severity',models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High'),('critical','Critical')],default='medium',max_length=20)),('status',models.CharField(choices=[('open','Open'),('investigating','Investigating'),('contained','Contained'),('resolved','Resolved'),('false_positive','False Positive')],default='open',max_length=30)),('summary',models.TextField(blank=True)),('evidence',models.JSONField(blank=True,default=list)),('opened_at',models.DateTimeField(auto_now_add=True)),('resolved_at',models.DateTimeField(blank=True,null=True)),('updated_at',models.DateTimeField(auto_now=True)),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='security_incidents_assigned',to='accounts.user')),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='security_incidents',to='accounts.company'))]),
      migrations.CreateModel(name='ThreatIndicator',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('indicator_type',models.CharField(choices=[('ip','IP'),('domain','Domain'),('hash','File Hash'),('user_agent','User Agent')],max_length=30)),('value_hash',models.CharField(db_index=True,max_length=64)),('label',models.CharField(blank=True,max_length=255)),('severity',models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High'),('critical','Critical')],default='high',max_length=20)),('active',models.BooleanField(default=True)),('source',models.CharField(default='internal',max_length=100)),('created_at',models.DateTimeField(auto_now_add=True)),('expires_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='threat_indicators',to='accounts.company'))]),
      migrations.CreateModel(name='RiskSignal',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('signal_type',models.CharField(max_length=120)),('score',models.PositiveSmallIntegerField(default=0)),('evidence',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('expires_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='risk_signals',to='accounts.company')),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='risk_signals',to='accounts.user'))]),
      migrations.CreateModel(name='DeviceTrust',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('device_hash',models.CharField(max_length=64)),('label',models.CharField(blank=True,max_length=200)),('state',models.CharField(choices=[('unknown','Unknown'),('trusted','Trusted'),('untrusted','Untrusted'),('blocked','Blocked')],default='unknown',max_length=20)),('last_ip',models.GenericIPAddressField(blank=True,null=True)),('last_seen_at',models.DateTimeField(auto_now=True)),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='accounts.user')),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='trusted_devices',to='accounts.company')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='trusted_devices',to='accounts.user'))]),
      migrations.CreateModel(name='AccessRole',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('permissions',models.JSONField(default=list)),('privileged',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='security_roles',to='accounts.company'))]),
      migrations.CreateModel(name='AccessRequest',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('requested_permissions',models.JSONField(default=list)),('reason',models.TextField()),('status',models.CharField(choices=[('pending','Pending'),('approved','Approved'),('rejected','Rejected'),('expired','Expired'),('revoked','Revoked')],default='pending',max_length=20)),('expires_at',models.DateTimeField()),('created_at',models.DateTimeField(auto_now_add=True)),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='approved_access_requests',to='accounts.user')),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='access_requests',to='accounts.company')),('requester',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='access_requests',to='accounts.user')),('target_user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='access_grants',to='accounts.user'))]),
      migrations.CreateModel(name='PAMSession',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('permissions',models.JSONField(default=list)),('started_at',models.DateTimeField(auto_now_add=True)),('expires_at',models.DateTimeField()),('revoked_at',models.DateTimeField(blank=True,null=True)),('emergency',models.BooleanField(default=False)),('access_request',models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='security.accessrequest')),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='pam_sessions',to='accounts.company')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='pam_sessions',to='accounts.user'))]),
      migrations.CreateModel(name='SSOProvider',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('provider_type',models.CharField(choices=[('oidc','OIDC'),('saml','SAML'),('entra','Microsoft Entra ID'),('google','Google Workspace')],max_length=30)),('name',models.CharField(max_length=120)),('domain',models.CharField(max_length=255)),('config_encrypted',models.TextField()),('enabled',models.BooleanField(default=False)),('group_role_mapping',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='sso_providers',to='accounts.company'))]),
      migrations.CreateModel(name='SCIMCredential',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('token_hash',models.CharField(max_length=64,unique=True)),('label',models.CharField(max_length=120)),('active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('last_used_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='scim_credentials',to='accounts.company'))]),
      migrations.CreateModel(name='AccessReview',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=200)),('status',models.CharField(choices=[('open','Open'),('closed','Closed')],default='open',max_length=20)),('due_at',models.DateTimeField()),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='access_reviews',to='accounts.company'))]),
      migrations.CreateModel(name='AccessCertification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('permissions_snapshot',models.JSONField(default=list)),('decision',models.CharField(choices=[('pending','Pending'),('certified','Certified'),('revoked','Revoked'),('change_requested','Change Requested')],default='pending',max_length=30)),('reason',models.TextField(blank=True)),('decided_at',models.DateTimeField(blank=True,null=True)),('decided_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='accounts.user')),('review',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='certifications',to='security.accessreview')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='access_certifications',to='accounts.user'))]),
      migrations.CreateModel(name='DLPPolicy',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('active',models.BooleanField(default=True)),('sensitive_fields',models.JSONField(blank=True,default=list)),('bulk_threshold',models.PositiveIntegerField(default=100)),('block_external_share',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='dlp_policies',to='accounts.company'))]),
      migrations.CreateModel(name='DLPEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('event_type',models.CharField(max_length=100)),('object_type',models.CharField(max_length=100)),('object_count',models.PositiveIntegerField(default=1)),('blocked',models.BooleanField(default=False)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='dlp_events',to='accounts.company')),('user',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to='accounts.user'))]),
      migrations.CreateModel(name='ResponsePlaybook',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('action',models.CharField(max_length=80)),('enabled',models.BooleanField(default=False)),('requires_approval',models.BooleanField(default=True)),('config',models.JSONField(blank=True,default=dict)),('company',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='response_playbooks',to='accounts.company'))]),
      migrations.CreateModel(name='ResponseAction',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(default='pending',max_length=20)),('result',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('executed_at',models.DateTimeField(blank=True,null=True)),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='response_approvals',to='accounts.user')),('incident',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='security.securityincident')),('playbook',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='actions',to='security.responseplaybook')),('requested_by',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='response_requests',to='accounts.user'))]),
      migrations.AddConstraint(model_name='devicetrust',constraint=models.UniqueConstraint(fields=('company','user','device_hash'),name='uniq_device_per_user_company')),
      migrations.AddConstraint(model_name='accessrole',constraint=models.UniqueConstraint(fields=('company','name'),name='uniq_security_role_company_name')),
      migrations.AddIndex(model_name='securityevent',index=models.Index(fields=('company','event_type','created_at'),name='security_event_company_event_idx')),
      migrations.AddIndex(model_name='securityevent',index=models.Index(fields=('severity','created_at'),name='security_event_severity_created_idx')),
    ]
