# Generated by Django 5.2.17 on 2026-09-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_company_fbded0_idx',
            old_name='security_event_company_event_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_severit_187aea_idx',
            old_name='security_event_severity_created_idx',
        ),
    ]
