# Generated by Django 5.2.17 on 2026-09-29 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_securityevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysession',
            name='mfa_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=254)),
                ('identifier_type', models.CharField(choices=[('username', 'Username'), ('ip', 'IP address')], default='username', max_length=10)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identifier_type', 'locked_until'], name='security_lo_identif_d6a02b_idx')],
                'unique_together': {('identifier', 'identifier_type')},
            },
        ),
    ]
