# Generated by Django 5.2.17 on 2026-09-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_document_lifecycle_security'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aidraft',
            new_name='ai_aidraft_company_203818_idx',
            old_name='ai_aidraft_company_9a1b7f_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='ai_knowledg_company_223032_idx',
            old_name='ai_knowled_company_8a7a3f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='knowledgechunk',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_ai_knowledge_chunk'),
        ),
    ]
