# Generated by Django 5.2.17 on 2026-09-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_rename_ai_aidraft_company_9a1b7f_idx_ai_aidraft_company_203818_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='chat_model',
            field=models.CharField(default='nvidia/nemotron-3-super-120b-a12b', max_length=200),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='embedding_model',
            field=models.CharField(default='nvidia/nemotron-3-embed-1b', max_length=200),
        ),
    ]
