# Generated by Django 5.2.17 on 2026-10-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_move_retired_nvidia_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='provides_embeddings',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='provider',
            field=models.CharField(choices=[('nvidia_nim', 'NVIDIA NIM'), ('openrouter', 'OpenRouter')], default='nvidia_nim', max_length=40),
        ),
    ]
