import { useEffect, useMemo, useState } from 'react';
import { api } from '../api/client';
import EmployeePicker from '../components/EmployeePicker';
import Icon from '../components/Icon';

const labels = { present:'Present', absent:'Absent', half_day:'Half day', leave:'On leave' };
export default function Attendance() {
  const [records,setRecords]=useState([]), [employees,setEmployees]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('');
  const [form,setForm]=useState({employee:'',date:new Date().toISOString().slice(0,10),status:'present'});
  function load(){setLoading(true);Promise.all([api.get('/attendance/records/'),api.get('/employees/employees/')]).then(([r,e])=>{setRecords(r.results??r);setEmployees(e.results??e)}).catch(err=>setError(err.message||'Failed to load attendance.')).finally(()=>setLoading(false));}
  useEffect(load,[]);
  async function submit(e){e.preventDefault();setError('');try{await api.post('/attendance/records/',form);setForm({employee:'',date:new Date().toISOString().slice(0,10),status:'present'});load()}catch(err){setError(err.message||'Failed to record attendance.')}}
  const summary=useMemo(()=>({present:records.filter(r=>r.status==='present').length,absent:records.filter(r=>r.status==='absent').length,half:records.filter(r=>r.status==='half_day').length,leave:records.filter(r=>r.status==='leave').length}),[records]);
  return <div className="workspace-page">
    <section className="welcome-row"><div><div className="eyebrow">WORKFORCE OPERATIONS</div><h1>Attendance</h1><p>Capture daily presence and keep an operational history by employee.</p></div><button className="btn btn-primary" onClick={()=>document.getElementById('attendance-entry')?.scrollIntoView({behavior:'smooth'})}><Icon name="clock" size={15}/>Record attendance</button></section>
    {error&&<div className="alert alert-error">{error}</div>}
    <div className="dash-stats"><div className="dash-stat"><div className="stat-icon"><Icon name="users"/></div><div className="stat-copy"><span>Employees</span><strong>{employees.length}</strong><small>Available to record</small></div></div><div className="dash-stat"><div className="stat-icon"><Icon name="clock"/></div><div className="stat-copy"><span>Present</span><strong>{summary.present}</strong><small>Recorded entries</small></div></div><div className="dash-stat"><div className="stat-icon"><Icon name="calendar"/></div><div className="stat-copy"><span>On leave</span><strong>{summary.leave}</strong><small>Attendance entries</small></div></div><div className="dash-stat"><div className="stat-icon"><Icon name="file"/></div><div className="stat-copy"><span>Exceptions</span><strong>{summary.absent+summary.half}</strong><small>Absent + half day</small></div></div></div>
    <section className="panel form-panel" id="attendance-entry"><div className="panel-head"><div><h2>Record attendance</h2><p>Use one record per employee and date.</p></div></div><form onSubmit={submit}><div className="form-row"><div><label>Employee (ID no / code / name)</label><EmployeePicker value={form.employee} required onChange={(id)=>setForm({...form,employee:id})}/></div><div><label>Date</label><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></div><div><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="form-action"><button className="btn btn-primary" type="submit">Save record</button></div></div></form></section>
    <section className="panel table-panel"><div className="panel-head"><div><h2>Attendance history <span className="count-pill">{records.length}</span></h2><p>Latest records across your accessible workforce.</p></div></div><div className="table-wrap"><table className="modern-table"><thead><tr><th>Employee</th><th>Date</th><th>Status</th></tr></thead><tbody>{loading?<tr><td colSpan="3" className="empty-row">Loading attendance…</td></tr>:records.map(r=><tr key={r.id}><td><div className="person-cell"><div className="avatar">{(r.employee_name||'E').slice(0,1)}</div><strong>{r.employee_name}</strong></div></td><td>{r.date}</td><td><span className={`status-dot status-${r.status}`}><i/>{labels[r.status]||r.status}</span></td></tr>)}{!loading&&!records.length&&<tr><td colSpan="3" className="empty-row">No attendance records yet.</td></tr>}</tbody></table></div></section>
  </div>;
}
