import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api/client';
import Icon from '../components/Icon';

const DOC_TYPES=[['identity','Identity'],['contract','Contract'],['certificate','Certificate'],['qualification','Qualification'],['policy','Policy / acknowledgement'],['medical','Medical / fitness'],['disciplinary','Disciplinary'],['other','Other']];
const CONTRACTS=[['','All contract types'],['full_time','Full-time'],['part_time','Part-time'],['contractor','Contractor'],['internship','Internship'],['temporary','Temporary']];
function scoreClass(v){return v>=90?'good':v>=70?'warn':'bad'}
function date(v){return v?new Date(`${v}T00:00:00`).toLocaleDateString():'—'}
export default function Compliance(){
 const [data,setData]=useState(null); const [employees,setEmployees]=useState([]); const [rules,setRules]=useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const [form,setForm]=useState({name:'',document_type:'identity',contract_type:'',employee:'',warning_days:30,is_active:true});
 async function load(){setLoading(true);setError('');try{const [c,e,r]=await Promise.all([api.get('/employees/compliance-dashboard/'),api.get('/employees/employees/'),api.get('/employees/compliance-rules/')]);setData(c);setEmployees(e.results??e);setRules(r.results??r)}catch(err){setError(err.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function createRule(e){e.preventDefault();setSaving(true);setError('');try{await api.post('/employees/compliance-rules/',{...form,employee:form.employee?Number(form.employee):null,warning_days:Number(form.warning_days)});setForm({name:'',document_type:'identity',contract_type:'',employee:'',warning_days:30,is_active:true});await load()}catch(err){setError(err.message)}finally{setSaving(false)}}
 async function toggleRule(rule){try{await api.patch(`/employees/compliance-rules/${rule.id}/`,{is_active:!rule.is_active});await load()}catch(err){setError(err.message)}}
 if(loading)return <div className="page-loading">Loading compliance center…</div>;
 const s=data?.summary||{};
 return <div className="page-shell">
  <section className="page-header"><div><div className="eyebrow">HR COMPLIANCE</div><h1>Documents & compliance</h1><p>Track required employee documents, expiry risk and contract deadlines from one place.</p></div><Link to="/employees" className="btn btn-secondary">Employee directory <Icon name="arrow" size={15}/></Link></section>
  {error&&<div className="alert error-alert">{error}</div>}
  <div className="dash-stats">
   <div className="dash-stat"><div className="stat-icon"><Icon name="shield"/></div><div className="stat-copy"><span>Average compliance</span><strong>{s.average_score??0}%</strong><small>{s.compliant??0} fully compliant</small></div></div>
   <div className="dash-stat"><div className="stat-icon"><Icon name="users"/></div><div className="stat-copy"><span>Needs attention</span><strong>{s.needs_attention??0}</strong><small>employees below 100%</small></div></div>
   <div className="dash-stat"><div className="stat-icon"><Icon name="file"/></div><div className="stat-copy"><span>Missing / expired</span><strong>{(s.missing_documents??0)+(s.expired_documents??0)}</strong><small>{s.missing_documents??0} missing · {s.expired_documents??0} expired</small></div></div>
   <div className="dash-stat"><div className="stat-icon"><Icon name="calendar"/></div><div className="stat-copy"><span>Open alerts</span><strong>{s.open_alerts??0}</strong><small>{s.expiring_documents??0} documents expiring soon</small></div></div>
  </div>
  <div className="dash-grid">
   <section className="panel"><div className="panel-head"><div><h2>Compliance alerts</h2><p>Missing, expired and upcoming deadlines</p></div></div>{data?.alerts?.length?<div className="activity-list">{data.alerts.slice(0,12).map((a,i)=><div className="activity-row" key={`${a.category}-${a.employee_id}-${a.title}-${i}`}><div className={`activity-icon compliance-alert-icon ${a.severity}`}><Icon name={a.severity==='critical'?'alert':'calendar'} size={16}/></div><div><strong>{a.title}</strong><small>{a.employee_name} · {a.details}{a.due_date?` · ${date(a.due_date)}`:''}</small></div><Link to={`/employees/${a.employee_id}`} className="text-link">Open</Link></div>)}</div>:<div className="empty-state"><div className="empty-icon"><Icon name="shield"/></div><strong>No compliance alerts</strong><p>Your current employee records have no missing or near-term compliance issues.</p></div>}</section>
   <section className="panel"><div className="panel-head"><div><h2>Employee compliance</h2><p>Individual compliance scores</p></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Employee</th><th>Score</th><th>Missing</th><th>Expired</th><th>Expiring</th></tr></thead><tbody>{(data?.employees||[]).map(e=><tr key={e.employee_id}><td><Link to={`/employees/${e.employee_id}`} className="text-link"><strong>{e.employee_name}</strong></Link><small>{e.department||e.employee_code}</small></td><td><span className={`compliance-score ${scoreClass(e.score)}`}>{e.score}%</span></td><td>{e.missing_count}</td><td>{e.expired_count}</td><td>{e.expiring_count}</td></tr>)}{!data?.employees?.length&&<tr><td colSpan="5" className="empty-row">No employees found.</td></tr>}</tbody></table></div></section>
  </div>
  <section className="panel"><div className="panel-head"><div><div className="eyebrow">COMPLIANCE RULES</div><h2>Required-document rules</h2><p>Create requirements for everyone, a contract type, or one specific employee.</p></div></div>
   <form className="form-panel" onSubmit={createRule}><div className="form-row"><div><label>Rule / document name</label><input required placeholder="e.g. Passport" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label>Document type</label><select value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}>{DOC_TYPES.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div><div><label>Contract scope</label><select value={form.contract_type} onChange={e=>setForm({...form,contract_type:e.target.value})}>{CONTRACTS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div></div><div className="form-row"><div><label>Specific employee (optional)</label><select value={form.employee} onChange={e=>setForm({...form,employee:e.target.value})}><option value="">All employees</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name} · {e.employee_code}</option>)}</select></div><div><label>Alert before expiry (days)</label><input type="number" min="0" max="365" value={form.warning_days} onChange={e=>setForm({...form,warning_days:e.target.value})}/></div><div className="form-check"><label><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active rule</label></div></div><button className="btn btn-primary compact" disabled={saving}>{saving?'Saving…':'Create requirement'}</button></form>
   <div className="table-wrap"><table className="data-table"><thead><tr><th>Rule</th><th>Scope</th><th>Warning</th><th>Status</th><th></th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.document_type_label}</small></td><td>{r.employee_name||r.contract_type_label||'All employees'}</td><td>{r.warning_days} days</td><td><span className={`badge ${r.is_active?'badge-paid':'badge-draft'}`}>{r.is_active?'Active':'Paused'}</span></td><td><button className="btn btn-secondary compact" onClick={()=>toggleRule(r)}>{r.is_active?'Pause':'Activate'}</button></td></tr>)}{!rules.length&&<tr><td colSpan="5" className="empty-row">No compliance rules yet.</td></tr>}</tbody></table></div>
  </section>
 </div>
}
