import { useEffect, useMemo, useState } from 'react';
import { api } from '../api/client';
import Icon from '../components/Icon';
const STATUS={active:'Active',on_leave:'On leave',suspended:'Suspended',terminated:'Terminated',resigned:'Resigned'};
export default function Departments(){
 const [departments,setDepartments]=useState([]),[selected,setSelected]=useState(null),[employees,setEmployees]=useState([]),[warnings,setWarnings]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[showForm,setShowForm]=useState(false);
 const [form,setForm]=useState({name:'',description:''}); const [warningForm,setWarningForm]=useState({employee:'',warning_level:'first',subject:'',incident_date:'',issued_date:new Date().toISOString().slice(0,10),details:''});
 async function loadDepartments(){setLoading(true);try{const d=await api.get('/employees/departments/');setDepartments(d.results??d)}catch(e){setError(e.message||'Failed to load departments.')}finally{setLoading(false)}} useEffect(()=>{loadDepartments()},[]);
 async function openDepartment(d){setSelected(d);setError('');try{const [e,w]=await Promise.all([api.get(`/employees/employees/?department=${encodeURIComponent(d.name)}`),api.get(`/employees/warning-letters/?department=${encodeURIComponent(d.name)}`)]);setEmployees(e.results??e);setWarnings(w.results??w)}catch(e){setError(e.message||'Failed to load department.')}}
 async function createDepartment(e){e.preventDefault();setError('');try{await api.post('/employees/departments/',form);setForm({name:'',description:''});setShowForm(false);loadDepartments()}catch(err){setError(err.message||'Failed to create department.')}}
 async function issueWarning(e){e.preventDefault();setError('');try{await api.post('/employees/warning-letters/',warningForm);setWarningForm({employee:'',warning_level:'first',subject:'',incident_date:'',issued_date:new Date().toISOString().slice(0,10),details:''});openDepartment(selected)}catch(err){setError(err.message||'Failed to issue warning letter.')}}
 const stats=useMemo(()=>({total:employees.length,active:employees.filter(e=>e.employment_status==='active').length,leave:employees.filter(e=>e.employment_status==='on_leave').length,warnings:warnings.length}),[employees,warnings]);
 if(selected) return <div className="workspace-page">
  <section className="welcome-row"><div><button className="btn-link breadcrumb-link" onClick={()=>setSelected(null)}>← All departments</button><div className="eyebrow">DEPARTMENT OPERATIONS</div><h1>{selected.name}</h1><p>{selected.description||'Manage team records, contracts, attendance, leave and employee relations.'}</p></div><button className="btn btn-secondary" onClick={()=>openDepartment(selected)}><Icon name="trend" size={15}/>Refresh</button></section>
  {error&&<div className="alert alert-error">{error}</div>}
  <div className="dash-stats"><div className="dash-stat"><div className="stat-icon"><Icon name="users"/></div><div className="stat-copy"><span>Total employees</span><strong>{stats.total}</strong><small>In this department</small></div></div><div className="dash-stat"><div className="stat-icon"><Icon name="grid"/></div><div className="stat-copy"><span>Active</span><strong>{stats.active}</strong><small>Current workforce</small></div></div><div className="dash-stat"><div className="stat-icon"><Icon name="calendar"/></div><div className="stat-copy"><span>On leave</span><strong>{stats.leave}</strong><small>Current status</small></div></div><div className="dash-stat"><div className="stat-icon"><Icon name="file"/></div><div className="stat-copy"><span>Warnings</span><strong>{stats.warnings}</strong><small>Employee relations</small></div></div></div>
  <section className="panel table-panel"><div className="panel-head"><div><h2>Department roster <span className="count-pill">{employees.length}</span></h2><p>Employment, contract, attendance and request history in one view.</p></div></div><div className="table-wrap"><table className="modern-table dept-table"><thead><tr><th>Employee</th><th>ID card</th><th>Job title</th><th>Status</th><th>Contract</th><th>Start</th><th>End</th><th>Attendance</th><th>Leave</th><th>Breaks</th><th>Warnings</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td><div className="person-cell"><div className="avatar">{e.full_name?.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{e.full_name}</strong><small>{e.employee_code}</small></div></div></td><td>{e.id_card_no||'—'}</td><td>{e.job_title||'—'}</td><td><span className={`status-dot status-${e.employment_status}`}><i/>{STATUS[e.employment_status]||e.employment_status}</span></td><td><span className={`mini-status ${e.contract_status}`}>{e.contract_status}</span></td><td>{e.contract_start_date||'—'}</td><td>{e.contract_end_date||'Open-ended'}</td><td>{e.attendance_count}</td><td>{e.leave_request_count}</td><td>{e.break_request_count}</td><td>{e.warning_letter_count}</td></tr>)}{!employees.length&&<tr><td colSpan="11" className="empty-row">No employees in this department.</td></tr>}</tbody></table></div></section>
  <div className="two-column-panels"><section className="panel form-panel"><div className="panel-head"><div><h2>Issue warning letter</h2><p>Keep employee-relations actions documented.</p></div></div><form onSubmit={issueWarning}><div className="form-row"><div><label>Employee</label><select value={warningForm.employee} onChange={e=>setWarningForm({...warningForm,employee:e.target.value})} required><option value="">Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></div><div><label>Warning level</label><select value={warningForm.warning_level} onChange={e=>setWarningForm({...warningForm,warning_level:e.target.value})}><option value="verbal">Verbal</option><option value="first">First written</option><option value="final">Final written</option><option value="disciplinary">Disciplinary</option></select></div></div><div className="form-row"><div><label>Subject</label><input value={warningForm.subject} onChange={e=>setWarningForm({...warningForm,subject:e.target.value})} required/></div><div><label>Incident date</label><input type="date" value={warningForm.incident_date} onChange={e=>setWarningForm({...warningForm,incident_date:e.target.value})}/></div></div><label>Details</label><textarea value={warningForm.details} onChange={e=>setWarningForm({...warningForm,details:e.target.value})} rows="5" required/><button className="btn btn-primary" type="submit">Issue warning</button></form></section>
  <section className="panel table-panel"><div className="panel-head"><div><h2>Recent warnings</h2><p>Latest employee-relations records.</p></div></div><div className="table-wrap"><table className="modern-table"><thead><tr><th>Employee</th><th>Level</th><th>Subject</th><th>Issued</th></tr></thead><tbody>{warnings.map(w=><tr key={w.id}><td>{w.employee_name}</td><td>{w.warning_level}</td><td>{w.subject}</td><td>{w.issued_date}</td></tr>)}{!warnings.length&&<tr><td colSpan="4" className="empty-row">No warning letters.</td></tr>}</tbody></table></div></section></div>
 </div>;
 return <div className="workspace-page"><section className="welcome-row"><div><div className="eyebrow">PEOPLE STRUCTURE</div><h1>Departments</h1><p>Give every team a clear operational home for headcount, contracts, attendance, leave and employee relations.</p></div><button className="btn btn-primary" onClick={()=>setShowForm(!showForm)}><Icon name="building" size={15}/>{showForm?'Close':'Add department'}</button></section>{error&&<div className="alert alert-error">{error}</div>}{showForm&&<section className="panel form-panel"><form onSubmit={createDepartment}><div className="form-row"><div><label>Department name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div><label>Description</label><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="form-action"><button className="btn btn-primary" type="submit">Create department</button></div></div></form></section>}
 <div className="department-grid">{loading?<div className="empty-state"><strong>Loading departments…</strong></div>:departments.map((d)=><button className="department-tile" key={d.id} onClick={()=>openDepartment(d)}><div className="department-tile-head"><div className="department-icon"><Icon name="building"/></div><span className="tile-arrow"><Icon name="arrow" size={15}/></span></div><h3>{d.name}</h3><p>{d.description||'No description yet.'}</p><div className="department-tile-foot"><strong>{d.employee_count}</strong><span>employees</span></div></button>)}{!loading&&!departments.length&&<div className="empty-state"><div className="empty-icon"><Icon name="building"/></div><strong>No departments yet</strong><p>Create your first department to start organizing the workforce.</p></div>}</div></div>;
}
