import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api, downloadFile } from '../api/client';
import Icon from '../components/Icon';
import { money, sumMoney } from '../utils/money';

const nice=v=>(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const date=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—';

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

async function downloadPdf(path, filename) {
  const { blob } = await downloadFile(path);
  downloadBlob(blob, filename);
}

function Badge({value}){return <span className={`badge badge-${value}`}>{nice(value)}</span>}
function Section({title,eyebrow,action,children}){return <section className="profile-section panel"><div className="panel-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2></div>{action}</div>{children}</section>}

export default function EmployeeProfile(){
 const {id}=useParams(), navigate=useNavigate();
 const [data,setData]=useState(null),[tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [departments,setDepartments]=useState([]),[details,setDetails]=useState({}),[core,setCore]=useState({});
 const [salary,setSalary]=useState({new_salary:'',effective_date:'',reason:''}),[position,setPosition]=useState({job_title:'',department_obj:'',effective_date:'',reason:''});
 const [doc,setDoc]=useState({document_type:'other',title:'',issue_date:'',expiry_date:'',notes:'',file:null});
 const [warningResponse,setWarningResponse]=useState({});
 const [warningForm,setWarningForm]=useState({warning_level:'first',subject:'',incident_date:'',issued_date:'',details:''});
 const [contractRenew,setContractRenew]=useState({});
 const [contract,setContract]=useState({contract_type:'full_time',start_date:new Date().toISOString().slice(0,10),end_date:'',notes:'',document:null});
 const [statutory,setStatutory]=useState({identifiers:{},tax_region:'',social_security_region:'',bank_name:'',bank_branch:'',account_name:'',mobile_money_provider:'',mobile_money_number:'',notes:''});

 const load=async()=>{setLoading(true);try{const [d,ds]=await Promise.all([api.get(`/employees/employees/${id}/360/`),api.get('/employees/departments/')]);setData(d);setDepartments(ds.results||ds||[]);}catch(e){setError(e.message||'Unable to load employee.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[id]);
 const employee=data?.employee;
 useEffect(()=>{if(employee){setCore({employee_code:employee.employee_code||'',id_card_no:employee.id_card_no||'',first_name:employee.first_name||'',last_name:employee.last_name||'',email:employee.email||'',phone:employee.phone||'',job_title:employee.job_title||'',pay_point:employee.pay_point||'',bank_account_number:employee.bank_account_number||'',base_salary:employee.base_salary||'',hire_date:employee.hire_date||'',employment_status:employee.employment_status||'active'});setPosition({job_title:employee.job_title||'',department_obj:employee.department_obj||'',effective_date:'',reason:''});setSalary({new_salary:employee.base_salary||'',effective_date:'',reason:''})}const p=data?.personal_details||{};const sp=data?.statutory_profile||{};setStatutory({identifiers:sp.identifiers||{},tax_region:sp.tax_region||'',social_security_region:sp.social_security_region||'',bank_name:sp.bank_name||'',bank_branch:sp.bank_branch||'',account_name:sp.account_name||'',mobile_money_provider:sp.mobile_money_provider||'',mobile_money_number:sp.mobile_money_number||'',notes:sp.notes||''});setDetails({...p,date_of_birth:p.date_of_birth||'',gender:p.gender||'',marital_status:p.marital_status||'',nationality:p.nationality||'',address_line_1:p.address_line_1||'',address_line_2:p.address_line_2||'',city:p.city||'',state_region:p.state_region||'',postal_code:p.postal_code||'',country:p.country||'',notes:p.notes||''})},[data]);
 const refresh=()=>api.get(`/employees/employees/${id}/360/`).then(setData);
 const submit=async(fn)=>{setSaving(true);setError('');try{await fn();await refresh()}catch(e){setError(e.message||'Action failed.')}finally{setSaving(false)}};
 async function saveCore(e){e.preventDefault();await submit(()=>api.patch(`/employees/employees/${id}/`,core))}
 async function saveStatutory(e){e.preventDefault();const body={...statutory,employee:id};await submit(()=>data.statutory_profile?api.patch(`/employees/statutory-profiles/${data.statutory_profile.id}/`,body):api.post('/employees/statutory-profiles/',body))}
 async function saveDetails(e){e.preventDefault();await submit(()=>api.patch(data.personal_details?`/employees/personal-details/${data.personal_details.id}/`:'/employees/personal-details/',data.personal_details?details:{...details,employee:id}))}
 async function changeSalary(e){e.preventDefault();await submit(()=>api.post(`/employees/employees/${id}/salary-change/`,salary));setTab('activity')}
 async function changePosition(e){e.preventDefault();await submit(()=>api.post(`/employees/employees/${id}/position-change/`,position));setTab('activity')}
 async function uploadPhoto(e){
  const file = e.target.files?.[0];
  if (!file) return;
  setError('');
  const fd = new FormData();
  fd.append('photo', file);
  try {
    await api.upload(`/employees/employees/${id}/photo/`, fd);
    await refresh();
  } catch (err) {
    setError(err.message || 'Photo upload failed');
  } finally {
    e.target.value = '';
  }
 }
 async function removePhoto(){
  setError('');
  try {
    await api.del(`/employees/employees/${id}/photo/`);
    await refresh();
  } catch (err) {
    setError(err.message || 'Could not remove photo');
  }
 }
 async function deleteEmployee(){
  if(!window.confirm(`Are you sure you want to permanently delete ${employee.full_name}? This action is irreversible and will remove all contracts and payroll history.`))return;
  setError('');
  try{
    await api.del(`/employees/employees/${id}/`);
    navigate('/employees');
  }catch(e){
    setError(e.message||'Failed to delete employee.');
  }
 }
 async function uploadDocument(e){e.preventDefault();if(!doc.file)return setError('Select a document first.');const fd=new FormData();fd.append('employee',id);fd.append('document_type',doc.document_type);fd.append('title',doc.title);fd.append('issue_date',doc.issue_date);fd.append('expiry_date',doc.expiry_date);fd.append('notes',doc.notes);fd.append('document',doc.file);await submit(()=>api.upload('/employees/documents/',fd));setDoc({document_type:'other',title:'',issue_date:'',expiry_date:'',notes:'',file:null})}
 async function renew(c){const f=contractRenew[c.id]||{};if(!f.end_date)return setError('Enter the new contract end date.');await submit(()=>api.post(`/employees/contracts/${c.id}/renew/`,f))}
 async function endContract(c){if(!window.confirm('End this contract?'))return;await submit(()=>api.post(`/employees/contracts/${c.id}/end/`,{end_date:new Date().toISOString().slice(0,10)}))}
 async function assignContract(e){e.preventDefault();const fd=new FormData();fd.append('employee',id);fd.append('contract_type',contract.contract_type);fd.append('start_date',contract.start_date);if(contract.end_date)fd.append('end_date',contract.end_date);if(contract.notes)fd.append('notes',contract.notes);if(contract.document)fd.append('document',contract.document);await submit(()=>api.upload('/employees/contracts/',fd));setContract({contract_type:'full_time',start_date:new Date().toISOString().slice(0,10),end_date:'',notes:'',document:null})}
 async function issueWarning(e){e.preventDefault();await submit(()=>api.post('/employees/warning-letters/',{...warningForm,employee:id,issued_date:warningForm.issued_date||new Date().toISOString().slice(0,10)}));setWarningForm({warning_level:'first',subject:'',incident_date:'',issued_date:'',details:''})}
 async function acknowledge(w){await submit(()=>api.post(`/employees/warning-letters/${w.id}/acknowledge/`,{employee_response:warningResponse[w.id]||w.employee_response||''}))}
 const current=data?.contracts?.find(c=>c.id===data.current_contract_id)||data?.contracts?.[0];
 const events=useMemo(()=>[...(data?.employment_events||[])].sort((a,b)=>`${b.effective_date}${b.created_at}`.localeCompare(`${a.effective_date}${a.created_at}`)),[data]);
 const initials=(employee?.full_name||'').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
 if(loading)return <div className="page-loading">Loading employee 360…</div>;
 if(!employee)return <div className="alert alert-error">Employee not found.</div>;
 return <div className="employee-profile-page">
  <button className="back-link" onClick={()=>navigate('/employees')}><Icon name="arrow" size={15}/> Back to employees</button>
  {error&&<div className="alert alert-error">{error}</div>}
  <div className="profile-hero panel"><div className="profile-hero-main"><div className="profile-avatar-wrap">
   <div className="profile-avatar-large">
     {employee.profile_photo_url
       ? <img src={employee.profile_photo_url} alt={employee.full_name} />
       : initials}
   </div>
   <label className="profile-photo-btn" title="Change photo">
     <input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={uploadPhoto} hidden />
     Photo
   </label>
   {employee.profile_photo_url && (
     <button type="button" className="btn-link profile-photo-remove" onClick={removePhoto}>Remove</button>
   )}
 </div><div className="profile-identity"><div className="eyebrow">EMPLOYEE 360</div><h1>{employee.full_name}</h1><p>{employee.job_title||'Employee'} · {employee.effective_department||'Unassigned department'}</p><div className="profile-tags"><Badge value={employee.employment_status}/><Badge value={employee.contract_status||'none'}/><span className="profile-code">{employee.employee_code}</span></div></div></div><div className="profile-actions"><button className="btn btn-secondary" onClick={()=>setTab('employment')}>HR actions</button><button className="btn btn-primary compact" onClick={()=>setTab('payroll')}>View payroll</button><button className="btn btn-danger compact" onClick={deleteEmployee}>Delete</button></div></div>
  <div className="profile-stats-grid"><div className="profile-stat"><span>Base salary</span><strong>{money(employee.base_salary)}</strong><small>current monthly base</small></div><div className="profile-stat"><span>Contract</span><strong>{nice(employee.contract_status||'none')}</strong><small>{date(employee.contract_end_date)} end</small></div><div className="profile-stat"><span>Warnings</span><strong>{employee.warning_letter_count||0}</strong><small>disciplinary records</small></div><div className="profile-stat"><span>Activity</span><strong>{events.length}</strong><small>HR lifecycle events</small></div></div>
  <div className="profile-tabs">{['overview','activity','employment','documents','hr-details','statutory','attendance','leave','compensation','payroll'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{nice(t)}</button>)}</div>

  {tab==='overview'&&<div className="profile-content-grid"><Section title="Employee snapshot" eyebrow="IDENTITY"><div className="detail-grid"><div><span>Name</span><strong>{employee.full_name}</strong></div><div><span>Employee ID</span><strong>{employee.employee_code}</strong></div><div><span>Email</span><strong>{employee.email||'—'}</strong></div><div><span>Phone</span><strong>{employee.phone||'—'}</strong></div><div><span>Position</span><strong>{employee.job_title||'—'}</strong></div><div><span>Department</span><strong>{employee.effective_department||'—'}</strong></div><div><span>Hire date</span><strong>{date(employee.hire_date)}</strong></div><div><span>Status</span><strong><Badge value={employee.employment_status}/></strong></div></div></Section><Section title="Current contract" eyebrow="EMPLOYMENT" action={<button className="btn btn-secondary compact" onClick={()=>setTab('employment')}>Manage</button>}>{current?<div className="contract-summary"><div className="contract-icon">⌁</div><div><strong>{nice(current.contract_type)}</strong><p>{date(current.start_date)} — {current.end_date?date(current.end_date):'Open ended'}</p></div><Badge value={current.status}/></div>:<div className="empty-state">No contract recorded.</div>}</Section><Section title="Recent HR activity" eyebrow="TIMELINE" action={<button className="btn btn-secondary compact" onClick={()=>setTab('activity')}>View timeline</button>}>{events.slice(0,5).map(e=><div className="activity-row" key={e.id}><div><strong>{e.title||e.event_type_label}</strong><small>{date(e.effective_date)} · {e.event_type_label}</small></div></div>)}{!events.length&&<div className="empty-state">No activity yet.</div>}</Section></div>}

  {tab==='activity'&&<Section title="Employee activity timeline" eyebrow="AUDITABLE HR HISTORY"><div className="timeline">{events.map(e=><div className="timeline-item" key={e.id}><div className="timeline-dot"/><div className="timeline-card"><div className="timeline-head"><strong>{e.title||e.event_type_label}</strong><span>{date(e.effective_date)}</span></div><div className="timeline-meta">{e.event_type_label}{e.created_by_name?` · ${e.created_by_name}`:''}</div>{e.description&&<p>{e.description}</p>}</div></div>)}{!events.length&&<div className="empty-state">No employee activity recorded.</div>}</div></Section>}

  {tab==='employment'&&<div className="profile-content-grid">
   <Section title="Salary change" eyebrow="COMPENSATION WORKFLOW"><form onSubmit={changeSalary} className="form-panel"><div className="form-row"><div><label>New base salary</label><input required type="number" min="0" step="0.01" value={salary.new_salary} onChange={e=>setSalary({...salary,new_salary:e.target.value})}/></div><div><label>Effective date</label><input required type="date" value={salary.effective_date} onChange={e=>setSalary({...salary,effective_date:e.target.value})}/></div></div><label>Reason</label><textarea required value={salary.reason} onChange={e=>setSalary({...salary,reason:e.target.value})}/><button className="btn btn-primary compact" disabled={saving}>Record salary change</button></form></Section>
   <Section title="Position / transfer" eyebrow="EMPLOYMENT WORKFLOW"><form onSubmit={changePosition} className="form-panel"><div className="form-row"><div><label>New job title</label><input required value={position.job_title} onChange={e=>setPosition({...position,job_title:e.target.value})}/></div><div><label>Department</label><select value={position.department_obj} onChange={e=>setPosition({...position,department_obj:e.target.value})}><option value="">Keep current department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div></div><div className="form-row"><div><label>Effective date</label><input required type="date" value={position.effective_date} onChange={e=>setPosition({...position,effective_date:e.target.value})}/></div></div><label>Reason</label><textarea required value={position.reason} onChange={e=>setPosition({...position,reason:e.target.value})}/><button className="btn btn-primary compact" disabled={saving}>Record position change</button></form></Section>
   <Section title="Assign employment contract" eyebrow="CONTRACT ASSIGNMENT"><form onSubmit={assignContract} className="form-panel"><p className="muted">Assign one dated contract at a time. End the current open-ended contract before adding the next term.</p><div className="form-row"><div><label>Contract type</label><select value={contract.contract_type} onChange={e=>setContract({...contract,contract_type:e.target.value})}><option value="full_time">Full-time</option><option value="part_time">Part-time</option><option value="contractor">Contractor</option><option value="internship">Internship</option><option value="temporary">Temporary</option></select></div><div><label>Start date</label><input required type="date" value={contract.start_date} onChange={e=>setContract({...contract,start_date:e.target.value})}/></div><div><label>End date</label><input type="date" min={contract.start_date} value={contract.end_date} onChange={e=>setContract({...contract,end_date:e.target.value})}/></div></div><div className="form-row"><div><label>Signed contract file</label><input type="file" accept=".pdf,.doc,.docx,image/*" onChange={e=>setContract({...contract,document:e.target.files?.[0]||null})}/></div></div><label>Notes</label><textarea value={contract.notes} onChange={e=>setContract({...contract,notes:e.target.value})} placeholder="Optional terms or assignment notes"/><button className="btn btn-primary compact" disabled={saving}>Assign contract</button></form></Section>
   <Section title="Contracts" eyebrow="CONTRACT HISTORY"><div className="table-wrap"><table className="data-table"><thead><tr><th>Type</th><th>Period</th><th>Status</th><th>File</th><th>Actions</th></tr></thead><tbody>{(data.contracts||[]).map(c=><tr key={c.id}><td>{nice(c.contract_type)}</td><td>{date(c.start_date)} — {c.end_date?date(c.end_date):'Open ended'}</td><td><Badge value={c.status}/></td><td>{c.document?<a href={c.document} target="_blank" rel="noreferrer">Open file</a>:'—'}</td><td><div className="button-row"><button className="btn btn-secondary compact" onClick={()=>setContractRenew({...contractRenew,[c.id]:{end_date:'',contract_type:c.contract_type}})}>Renew</button>{c.status==='active'&&<button className="btn btn-secondary compact" onClick={()=>endContract(c)}>End</button>}</div>{contractRenew[c.id]&&<div className="inline-editor"><input type="date" value={contractRenew[c.id].end_date||''} onChange={e=>setContractRenew({...contractRenew,[c.id]:{...contractRenew[c.id],end_date:e.target.value}})}/><button className="btn btn-primary compact" onClick={()=>renew(c)}>Save renewal</button></div>}</td></tr>)}{!data.contracts?.length&&<tr><td colSpan="5" className="empty-row">No contracts recorded.</td></tr>}</tbody></table></div></Section>
   <Section title="Issue warning letter" eyebrow="DISCIPLINARY WORKFLOW"><form onSubmit={issueWarning} className="form-panel"><div className="form-row"><div><label>Level</label><select value={warningForm.warning_level} onChange={e=>setWarningForm({...warningForm,warning_level:e.target.value})}><option value="verbal">Verbal warning</option><option value="first">First written warning</option><option value="final">Final written warning</option><option value="disciplinary">Disciplinary action</option></select></div><div><label>Subject</label><input required value={warningForm.subject} onChange={e=>setWarningForm({...warningForm,subject:e.target.value})}/></div><div><label>Incident date</label><input type="date" value={warningForm.incident_date} onChange={e=>setWarningForm({...warningForm,incident_date:e.target.value})}/></div></div><label>Details</label><textarea required value={warningForm.details} onChange={e=>setWarningForm({...warningForm,details:e.target.value})}/><button className="btn btn-primary compact" disabled={saving}>Issue warning</button></form></Section>
   <Section title="Warning letters" eyebrow="DISCIPLINARY RECORDS"><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Level</th><th>Subject</th><th>Status</th><th>Action</th></tr></thead><tbody>{(employee.warning_letters||[]).map(w=><tr key={w.id}><td>{date(w.issued_date)}</td><td>{nice(w.warning_level)}</td><td><strong>{w.subject}</strong></td><td><Badge value={w.acknowledged?'approved':'pending'}/></td><td>{w.acknowledged?'Acknowledged':<button className="btn btn-secondary compact" onClick={()=>acknowledge(w)}>Acknowledge</button>}</td></tr>)}{!employee.warning_letters?.length&&<tr><td colSpan="6" className="empty-row">No warning letters.</td></tr>}</tbody></table></div></Section>
  </div>}

  {tab==='documents'&&<div className="profile-content-grid"><Section title="Employee documents" eyebrow="HR DOCUMENTS"><div className="table-wrap"><table className="data-table"><thead><tr><th>Document</th><th>Type</th><th>Issue</th><th>Expiry</th><th>Status</th><th>File</th></tr></thead><tbody>{(data.documents||[]).map(d=><tr key={d.id}><td><strong>{d.title}</strong><small>{d.notes||''}</small></td><td>{d.document_type_label}</td><td>{date(d.issue_date)}</td><td>{date(d.expiry_date)}</td><td><span className={`badge badge-${d.status==='expired'?'failed':d.status==='expiring'?'pending':'paid'}`}>{d.status}</span></td><td>{d.document?<a href={d.document} target="_blank" rel="noreferrer">Open</a>:'—'}</td></tr>)}{!data.documents?.length&&<tr><td colSpan="6" className="empty-row">No employee documents uploaded.</td></tr>}</tbody></table></div></Section><Section title="Upload HR document" eyebrow="RECORD MANAGEMENT"><form onSubmit={uploadDocument} className="form-panel"><div className="form-row"><div><label>Document type</label><select value={doc.document_type} onChange={e=>setDoc({...doc,document_type:e.target.value})}>{[['identity','Identity'],['contract','Contract'],['certificate','Certificate'],['qualification','Qualification'],['policy','Policy / acknowledgement'],['medical','Medical / fitness'],['disciplinary','Disciplinary'],['other','Other']].map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></div><div><label>Title</label><input required value={doc.title} onChange={e=>setDoc({...doc,title:e.target.value})}/></div></div><div className="form-row"><div><label>Issue date</label><input type="date" value={doc.issue_date} onChange={e=>setDoc({...doc,issue_date:e.target.value})}/></div><div><label>Expiry date</label><input type="date" value={doc.expiry_date} onChange={e=>setDoc({...doc,expiry_date:e.target.value})}/></div><div><label>File</label><input required type="file" onChange={e=>setDoc({...doc,file:e.target.files?.[0]||null})}/></div></div><label>Notes</label><textarea value={doc.notes} onChange={e=>setDoc({...doc,notes:e.target.value})}/><button className="btn btn-primary compact" disabled={saving}>Upload document</button></form></Section></div>}

  {tab==='hr-details'&&<div className="profile-content-grid"><Section title="Payslip & pay details" eyebrow="CORE HR"><form onSubmit={saveCore}><div className="form-row"><div><label>Job title</label><input value={core.job_title} onChange={e=>setCore({...core,job_title:e.target.value})}/></div><div><label>ID Card No.</label><input value={core.id_card_no} onChange={e=>setCore({...core,id_card_no:e.target.value})}/></div></div><div className="form-row"><div><label>Pay point / duty station</label><input value={core.pay_point} onChange={e=>setCore({...core,pay_point:e.target.value})} placeholder="Shown on payslips and leave forms"/></div><div><label>Bank account number</label><input value={core.bank_account_number} onChange={e=>setCore({...core,bank_account_number:e.target.value})}/></div></div><button className="btn btn-primary compact" disabled={saving}>Save payslip details</button></form></Section><Section title="Personal & address details" eyebrow="CORE HR"><form onSubmit={saveDetails}><div className="form-row"><div><label>Date of birth</label><input type="date" value={details.date_of_birth} onChange={e=>setDetails({...details,date_of_birth:e.target.value})}/></div><div><label>Gender</label><select value={details.gender} onChange={e=>setDetails({...details,gender:e.target.value})}><option value="">Not specified</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="prefer_not_to_say">Prefer not to say</option></select></div><div><label>Nationality</label><input value={details.nationality} onChange={e=>setDetails({...details,nationality:e.target.value})}/></div></div><div className="form-row"><div><label>Country</label><input value={details.country} onChange={e=>setDetails({...details,country:e.target.value})}/></div><div><label>City</label><input value={details.city} onChange={e=>setDetails({...details,city:e.target.value})}/></div><div><label>Region</label><input value={details.state_region} onChange={e=>setDetails({...details,state_region:e.target.value})}/></div></div><div className="form-row"><div><label>Address</label><input value={details.address_line_1} onChange={e=>setDetails({...details,address_line_1:e.target.value})}/></div><div><label>Address line 2</label><input value={details.address_line_2} onChange={e=>setDetails({...details,address_line_2:e.target.value})}/></div><div><label>Postal code</label><input value={details.postal_code} onChange={e=>setDetails({...details,postal_code:e.target.value})}/></div></div><label>HR notes</label><textarea value={details.notes} onChange={e=>setDetails({...details,notes:e.target.value})}/><button className="btn btn-primary compact" disabled={saving}>Save HR details</button></form></Section></div>}

  {tab==='statutory'&&<div className="profile-content-grid"><Section title="Statutory & payment profile" eyebrow="COUNTRY-SPECIFIC EMPLOYEE DATA"><form onSubmit={saveStatutory}><p className="muted">These fields follow your company's country pack. Enter only identifiers relevant to the employee.</p><div className="form-row"><div><label>Tax region</label><input value={statutory.tax_region} onChange={e=>setStatutory({...statutory,tax_region:e.target.value})}/></div><div><label>Social security region</label><input value={statutory.social_security_region} onChange={e=>setStatutory({...statutory,social_security_region:e.target.value})}/></div></div><div className="form-row">{(data.statutory_fields||data.statutory_profile?.available_fields||[]).map(f=><div key={f.key}><label>{f.label}{f.required?' *':''}</label><input value={statutory.identifiers?.[f.key]||''} onChange={e=>setStatutory({...statutory,identifiers:{...statutory.identifiers,[f.key]:e.target.value}})}/></div>)}</div><div className="form-row"><div><label>Bank name</label><input value={statutory.bank_name} onChange={e=>setStatutory({...statutory,bank_name:e.target.value})}/></div><div><label>Bank branch</label><input value={statutory.bank_branch} onChange={e=>setStatutory({...statutory,bank_branch:e.target.value})}/></div><div><label>Account name</label><input value={statutory.account_name} onChange={e=>setStatutory({...statutory,account_name:e.target.value})}/></div></div><div className="form-row"><div><label>Mobile money provider</label><input value={statutory.mobile_money_provider} onChange={e=>setStatutory({...statutory,mobile_money_provider:e.target.value})}/></div><div><label>Mobile money number</label><input value={statutory.mobile_money_number} onChange={e=>setStatutory({...statutory,mobile_money_number:e.target.value})}/></div></div><label>Notes</label><textarea value={statutory.notes} onChange={e=>setStatutory({...statutory,notes:e.target.value})}/><button className="btn btn-primary compact" disabled={saving}>Save statutory profile</button></form></Section></div>}

  {tab==='attendance'&&<Section title="Attendance history" eyebrow="TIME & ATTENDANCE"><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Status</th><th>Check in</th><th>Check out</th><th>Notes</th></tr></thead><tbody>{(data.attendance||[]).map(a=><tr key={a.id}><td>{date(a.date)}</td><td><Badge value={a.status}/></td><td>{a.check_in||'—'}</td><td>{a.check_out||'—'}</td><td>{a.notes||'—'}</td></tr>)}</tbody></table></div></Section>}
  {tab==='leave'&&<Section title="Leave & breaks" eyebrow="TIME OFF">
<div className="table-wrap"><table className="data-table"><thead><tr><th>Type</th><th>Dates</th><th>Days</th><th>Status</th><th>PDF</th></tr></thead><tbody>
{(data.leave_requests||[]).map(r=><tr key={`l${r.id}`}><td>{nice(r.leave_type)}</td><td>{date(r.start_date)} — {date(r.end_date)}</td><td>{r.days_requested}</td><td><Badge value={r.status}/></td><td><button className="btn-link" onClick={()=>downloadPdf(`/leave/requests/${r.id}/pdf/?copy=employee`,`leave-request-${r.id}-employee.pdf`).catch(e=>setError(e.message))}>Employee</button>{' '}<button className="btn-link" onClick={()=>downloadPdf(`/leave/requests/${r.id}/pdf/?copy=company`,`leave-request-${r.id}-company.pdf`).catch(e=>setError(e.message))}>Company</button></td></tr>)}
{(data.break_requests||[]).map(r=><tr key={`b${r.id}`}><td>Break · {nice(r.break_type)}</td><td>{date(r.date)} {r.start_time||''}{r.end_time?` – ${r.end_time}`:''}</td><td>—</td><td><Badge value={r.status}/></td><td><button className="btn-link" onClick={()=>downloadPdf(`/leave/break-requests/${r.id}/pdf/?copy=employee`,`break-request-${r.id}-employee.pdf`).catch(e=>setError(e.message))}>Employee</button>{' '}<button className="btn-link" onClick={()=>downloadPdf(`/leave/break-requests/${r.id}/pdf/?copy=company`,`break-request-${r.id}-company.pdf`).catch(e=>setError(e.message))}>Company</button></td></tr>)}
{!(data.leave_requests||[]).length&&!(data.break_requests||[]).length&&<tr><td colSpan="5" className="empty-row">No leave or break requests yet.</td></tr>}
</tbody></table></div></Section>}
  {tab==='compensation'&&<Section title="Recurring compensation" eyebrow="PAY & BENEFITS"><div className="compensation-summary"><div><span>Base salary</span><strong>{money(employee.base_salary)}</strong></div><div><span>Allowances</span><strong>{employee.allowances?.length||0}</strong></div><div><span>Deductions</span><strong>{employee.deductions?.length||0}</strong></div></div><div className="line-list">{employee.allowances?.map(a=><div key={`a${a.id}`}><span>{a.name}</span><strong>+ {money(a.amount)}{a.is_percentage_of_base?'%':''}</strong></div>)}{employee.deductions?.map(d=><div key={`d${d.id}`}><span>{d.name}</span><strong>− {money(d.amount)}{d.is_percentage_of_base?'%':''}</strong></div>)}</div><p className="muted">Use Employment → Salary change for auditable base-salary changes. Recurring allowances and deductions remain part of payroll configuration.</p></Section>}
  {tab==='payroll'&&<Section title="Payroll history" eyebrow="PAYROLL"><div className="table-wrap"><table className="data-table"><thead><tr><th>Period</th><th>Gross</th><th>Tax</th><th>Deductions</th><th>Net</th><th>Payment</th><th>PDF</th></tr></thead><tbody>{(data.payslips||[]).map(s=><tr key={s.id}><td>{date(s.payroll_period_start)} — {date(s.payroll_period_end)}</td><td>{money(s.gross_salary)}</td><td>{money(s.tax_amount)}</td><td>{money(sumMoney([s], ['total_contributions', 'total_other_deductions']))}</td><td><strong>{money(s.net_salary)}</strong></td><td>{s.payment_method?nice(s.payment_method):'—'}</td><td><button className="btn-link" onClick={()=>downloadPdf(`/payroll/payslips/${s.id}/?download=pdf&copy=employee`,`payslip-${s.id}-employee.pdf`).catch(e=>setError(e.message))}>Employee</button>{' '}<button className="btn-link" onClick={()=>downloadPdf(`/payroll/payslips/${s.id}/?download=pdf&copy=company`,`payslip-${s.id}-company.pdf`).catch(e=>setError(e.message))}>Company</button></td></tr>)}{!(data.payslips||[]).length&&<tr><td colSpan="7" className="empty-row">No payslips yet.</td></tr>}</tbody></table></div></Section>}
 </div>
}
