import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client';
import Icon from '../components/Icon';
const tabs=[['tasks','Tasks'],['notifications','Notifications'],['rules','Automation rules']];
export default function Workflows(){
 const [tab,setTab]=useState('tasks'),[tasks,setTasks]=useState([]),[notes,setNotes]=useState([]),[rules,setRules]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[running,setRunning]=useState(false);
 async function load(){setLoading(true);try{const [t,n,r]=await Promise.all([api.get('/workflows/tasks/'),api.get('/workflows/notifications/'),api.get('/workflows/rules/')]);setTasks(t.results??t);setNotes(n.results??n);setRules(r.results??r)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 // These were unhandled: a failed click did nothing visible and the row stayed
 // exactly as it was, so there was no way to tell the change had not saved.
 async function complete(id){try{await api.post(`/workflows/tasks/${id}/complete/`);setError('');load()}catch(e){setError(e.message||'Could not complete the task.')}}
 async function read(id){try{await api.post(`/workflows/notifications/${id}/read/`);setError('');load()}catch(e){setError(e.message||'Could not mark the notification read.')}}
 async function run(){setRunning(true);try{await api.post('/workflows/rules/run_now/');await load()}catch(e){setError(e.message)}finally{setRunning(false)}}
 if(loading)return <div className="page-loading">Loading HR workflows…</div>;
 return <div className="page-shell"><section className="page-header"><div><div className="eyebrow">HR AUTOMATION</div><h1>Notifications & workflows</h1><p>Turn HR events into actionable tasks and timely notifications.</p></div><button className="btn btn-primary" onClick={run} disabled={running}><Icon name="trend" size={15}/>{running?'Running…':'Run automations now'}</button></section>
 {error&&<div className="alert error-alert">{error}</div>}
 <div className="dash-stats"><div className="dash-stat"><div className="stat-icon"><Icon name="file"/></div><div className="stat-copy"><span>Open tasks</span><strong>{tasks.filter(x=>['open','in_progress'].includes(x.status)).length}</strong><small>HR actions waiting</small></div></div><div className="dash-stat"><div className="stat-icon"><Icon name="bell"/></div><div className="stat-copy"><span>Unread</span><strong>{notes.filter(x=>!x.is_read).length}</strong><small>Notifications for you</small></div></div><div className="dash-stat"><div className="stat-icon"><Icon name="calendar"/></div><div className="stat-copy"><span>Due soon</span><strong>{tasks.filter(x=>x.due_date&&new Date(x.due_date+'T00:00:00')<=new Date(Date.now()+7*864e5)&&x.status!=='completed').length}</strong><small>Next 7 days</small></div></div></div>
 <div className="panel"><div className="tabs">{tabs.map(([k,l])=><button key={k} className={`tab ${tab===k?'active':''}`} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==='tasks'&&<div className="activity-list">{tasks.map(t=><div className="activity-row" key={t.id}><div className={`activity-icon ${t.priority==='urgent'?'danger':''}`}><Icon name={t.task_type==='compliance'?'shield':t.task_type==='leave'?'calendar':'file'} size={16}/></div><div><strong>{t.title}</strong><small>{t.employee_name||'Company task'} · {t.priority} · {t.due_date?`Due ${new Date(t.due_date+'T00:00:00').toLocaleDateString()}`:'No due date'}</small></div><div>{t.status==='completed'?<span className="badge badge-paid">Completed</span>:<button className="btn btn-secondary compact" onClick={()=>complete(t.id)}>Complete</button>}</div></div>)}{!tasks.length&&<div className="empty-state"><strong>No workflow tasks</strong><p>New employee onboarding, compliance and contract events will appear here.</p></div>}</div>}
 {tab==='notifications'&&<div className="activity-list">{notes.map(n=><div className={`activity-row ${n.is_read?'':'unread-row'}`} key={n.id}><div className={`activity-icon ${n.level==='danger'?'danger':''}`}><Icon name="bell" size={16}/></div><div><strong>{n.title}</strong><small>{n.message}{n.due_date?` · ${new Date(n.due_date+'T00:00:00').toLocaleDateString()}`:''}</small></div><div>{n.employee&&<Link className="text-link" to={`/employees/${n.employee}`}>Open</Link>}{!n.is_read&&<button className="btn btn-secondary compact" onClick={()=>read(n.id)}>Mark read</button>}</div></div>)}{!notes.length&&<div className="empty-state"><strong>No notifications</strong><p>You're all caught up.</p></div>}</div>}
 {tab==='rules'&&<div className="table-wrap"><table className="data-table"><thead><tr><th>Rule</th><th>Event</th><th>Task</th><th>Notification</th><th>Window</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.event_type_label}</td><td>{r.create_task?'Yes':'No'}</td><td>{r.send_notification?'Yes':'No'}</td><td>{r.days_before} days</td></tr>)}{!rules.length&&<tr><td colSpan="5" className="empty-row">No custom rules configured. Core automations remain active.</td></tr>}</tbody></table></div>}
 </div></div>
}
