# Generated by Django 5.1.15 on 2026-09-14 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', help_text='ISO currency code, e.g. GNF, NGN, KES, USD', max_length=10)),
                ('pay_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Bi-weekly'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('tax_calculation_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='accounts.company')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('payment_method', models.CharField(blank=True, help_text='e.g. bank_transfer, mobile_money, cash', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Social Security, Pension, Health Insurance', max_length=100)),
                ('is_percentage', models.BooleanField(default=True)),
                ('employee_rate', models.DecimalField(decimal_places=2, default=0, help_text='% or flat amount paid by employee', max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=2, default=0, help_text='% or flat amount paid by employer', max_digits=5)),
                ('payroll_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='payroll.payrollconfig')),
            ],
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage, e.g. 15.00 for 15%', max_digits=5)),
                ('payroll_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_brackets', to='payroll.payrollconfig')),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
    ]
