# Generated by Django 5.2.17 on 2026-10-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payslip_uniqueness_and_amount_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerule',
            name='standard_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
    ]
