# Generated by Django 5.2.17 on 2026-10-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_overtimerule_standard_hours_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconfig',
            name='deduct_unpaid_absence',
            field=models.BooleanField(default=False),
        ),
    ]
