# Generated by Django 5.2.17 on 2026-10-04 10:11

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_subscription_plan'),
        ('employees', '0011_alter_contract_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('company'), condition=models.Q(('email', ''), _negated=True), name='unique_employee_email_per_company_ci'),
        ),
    ]
