# Generated by Django 5.2.17 on 2026-09-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0006_payment_retry_and_rule_uniqueness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycountryprofile',
            options={'verbose_name': 'Company Country Profile', 'verbose_name_plural': 'Company Country Profiles'},
        ),
        migrations.AlterModelOptions(
            name='statutoryfilingpayment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='statutoryfiling',
            new_name='regional_st_company_b94146_idx',
            old_name='regional_statu_company_6d7f90_idx',
        ),
        migrations.RenameIndex(
            model_name='statutoryfilingpayment',
            new_name='regional_st_filing__b6172b_idx',
            old_name='regional_pa_filing__idx',
        ),
        migrations.RenameIndex(
            model_name='statutoryfilingrule',
            new_name='regional_st_country_1eb911_idx',
            old_name='regional_statu_country_7e65a1_idx',
        ),
        migrations.RenameIndex(
            model_name='statutoryrule',
            new_name='regional_st_country_40ef09_idx',
            old_name='regional_st_country_8e5b22_idx',
        ),
        migrations.RenameIndex(
            model_name='statutoryrule',
            new_name='regional_st_country_39ad6d_idx',
            old_name='regional_st_country_3f4b9c_idx',
        ),
    ]
