# Generated by Django 5.2.17 on 2026-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0007_alter_companycountryprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycountryprofile',
            name='country_code',
            field=models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('SL', 'Sierra Leone'), ('LR', 'Liberia'), ('GM', 'The Gambia'), ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('BW', 'Botswana'), ('NA', 'Namibia'), ('ZA', 'South Africa'), ('EG', 'Egypt')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statutorycompliancepack',
            name='country_code',
            field=models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('SL', 'Sierra Leone'), ('LR', 'Liberia'), ('GM', 'The Gambia'), ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('BW', 'Botswana'), ('NA', 'Namibia'), ('ZA', 'South Africa'), ('EG', 'Egypt')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statutoryfilingrule',
            name='country_code',
            field=models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('SL', 'Sierra Leone'), ('LR', 'Liberia'), ('GM', 'The Gambia'), ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('BW', 'Botswana'), ('NA', 'Namibia'), ('ZA', 'South Africa'), ('EG', 'Egypt')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statutoryrule',
            name='country_code',
            field=models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('SL', 'Sierra Leone'), ('LR', 'Liberia'), ('GM', 'The Gambia'), ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('BW', 'Botswana'), ('NA', 'Namibia'), ('ZA', 'South Africa'), ('EG', 'Egypt')], max_length=2),
        ),
    ]
