# Generated by Django 5.2.17 on 2026-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional', '0008_alter_companycountryprofile_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycountryprofile',
            name='country_code',
            field=models.CharField(choices=[('AO', 'Angola'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BW', 'Botswana'), ('CD', 'DR Congo'), ('CF', 'Central African Republic'), ('CG', 'Republic of the Congo'), ('CI', "Côte d'Ivoire"), ('CM', 'Cameroon'), ('CV', 'Cabo Verde'), ('DJ', 'Djibouti'), ('DZ', 'Algeria'), ('EG', 'Egypt'), ('ER', 'Eritrea'), ('ET', 'Ethiopia'), ('GA', 'Gabon'), ('GH', 'Ghana'), ('GM', 'The Gambia'), ('GN', 'Guinea'), ('GQ', 'Equatorial Guinea'), ('GW', 'Guinea-Bissau'), ('KE', 'Kenya'), ('KM', 'Comoros'), ('LR', 'Liberia'), ('LS', 'Lesotho'), ('LY', 'Libya'), ('MA', 'Morocco'), ('MG', 'Madagascar'), ('ML', 'Mali'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MW', 'Malawi'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('RW', 'Rwanda'), ('SC', 'Seychelles'), ('SD', 'Sudan'), ('SL', 'Sierra Leone'), ('SN', 'Senegal'), ('SO', 'Somalia'), ('SS', 'South Sudan'), ('ST', 'São Tomé and Príncipe'), ('SZ', 'Eswatini'), ('TD', 'Chad'), ('TG', 'Togo'), ('TN', 'Tunisia'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statutorycompliancepack',
            name='country_code',
            field=models.CharField(choices=[('AO', 'Angola'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BW', 'Botswana'), ('CD', 'DR Congo'), ('CF', 'Central African Republic'), ('CG', 'Republic of the Congo'), ('CI', "Côte d'Ivoire"), ('CM', 'Cameroon'), ('CV', 'Cabo Verde'), ('DJ', 'Djibouti'), ('DZ', 'Algeria'), ('EG', 'Egypt'), ('ER', 'Eritrea'), ('ET', 'Ethiopia'), ('GA', 'Gabon'), ('GH', 'Ghana'), ('GM', 'The Gambia'), ('GN', 'Guinea'), ('GQ', 'Equatorial Guinea'), ('GW', 'Guinea-Bissau'), ('KE', 'Kenya'), ('KM', 'Comoros'), ('LR', 'Liberia'), ('LS', 'Lesotho'), ('LY', 'Libya'), ('MA', 'Morocco'), ('MG', 'Madagascar'), ('ML', 'Mali'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MW', 'Malawi'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('RW', 'Rwanda'), ('SC', 'Seychelles'), ('SD', 'Sudan'), ('SL', 'Sierra Leone'), ('SN', 'Senegal'), ('SO', 'Somalia'), ('SS', 'South Sudan'), ('ST', 'São Tomé and Príncipe'), ('SZ', 'Eswatini'), ('TD', 'Chad'), ('TG', 'Togo'), ('TN', 'Tunisia'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statutoryfilingrule',
            name='country_code',
            field=models.CharField(choices=[('AO', 'Angola'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BW', 'Botswana'), ('CD', 'DR Congo'), ('CF', 'Central African Republic'), ('CG', 'Republic of the Congo'), ('CI', "Côte d'Ivoire"), ('CM', 'Cameroon'), ('CV', 'Cabo Verde'), ('DJ', 'Djibouti'), ('DZ', 'Algeria'), ('EG', 'Egypt'), ('ER', 'Eritrea'), ('ET', 'Ethiopia'), ('GA', 'Gabon'), ('GH', 'Ghana'), ('GM', 'The Gambia'), ('GN', 'Guinea'), ('GQ', 'Equatorial Guinea'), ('GW', 'Guinea-Bissau'), ('KE', 'Kenya'), ('KM', 'Comoros'), ('LR', 'Liberia'), ('LS', 'Lesotho'), ('LY', 'Libya'), ('MA', 'Morocco'), ('MG', 'Madagascar'), ('ML', 'Mali'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MW', 'Malawi'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('RW', 'Rwanda'), ('SC', 'Seychelles'), ('SD', 'Sudan'), ('SL', 'Sierra Leone'), ('SN', 'Senegal'), ('SO', 'Somalia'), ('SS', 'South Sudan'), ('ST', 'São Tomé and Príncipe'), ('SZ', 'Eswatini'), ('TD', 'Chad'), ('TG', 'Togo'), ('TN', 'Tunisia'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statutoryrule',
            name='country_code',
            field=models.CharField(choices=[('AO', 'Angola'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BW', 'Botswana'), ('CD', 'DR Congo'), ('CF', 'Central African Republic'), ('CG', 'Republic of the Congo'), ('CI', "Côte d'Ivoire"), ('CM', 'Cameroon'), ('CV', 'Cabo Verde'), ('DJ', 'Djibouti'), ('DZ', 'Algeria'), ('EG', 'Egypt'), ('ER', 'Eritrea'), ('ET', 'Ethiopia'), ('GA', 'Gabon'), ('GH', 'Ghana'), ('GM', 'The Gambia'), ('GN', 'Guinea'), ('GQ', 'Equatorial Guinea'), ('GW', 'Guinea-Bissau'), ('KE', 'Kenya'), ('KM', 'Comoros'), ('LR', 'Liberia'), ('LS', 'Lesotho'), ('LY', 'Libya'), ('MA', 'Morocco'), ('MG', 'Madagascar'), ('ML', 'Mali'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MW', 'Malawi'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('RW', 'Rwanda'), ('SC', 'Seychelles'), ('SD', 'Sudan'), ('SL', 'Sierra Leone'), ('SN', 'Senegal'), ('SO', 'Somalia'), ('SS', 'South Sudan'), ('ST', 'São Tomé and Príncipe'), ('SZ', 'Eswatini'), ('TD', 'Chad'), ('TG', 'Togo'), ('TN', 'Tunisia'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2),
        ),
    ]
